version: "3.8"

services:
  db:
    image: mysql
    container_name: local_mysqldb
    restart: always
    ports:
      - "6034:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - local_mysqldata:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks :
      - mysql-phpmyadmin
   
  phpadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8881:80"
    environment:
      PMA_HOST: db  
    networks:
      - mysql-phpmyadmin
   

networks:
    mysql-phpmyadmin:
      driver: bridge

volumes:
  local_mysqldata:


# pour lancer mon docker compose :
# docker-compose up -d

# pour arreter mon docker compose :
# docker-compose down