FROM nginx

WORKDIR /usr/share/nginx/html

EXPOSE 80

RUN apt-get update && apt-get install -y git

RUN rm -rf /usr/share/nginx/html/*

RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube.git . 

CMD [  "nginx","-g","daemon off;" ]