version: "3"

services:
  # Database
  bddBlog:
    container_name: bddBlogContainer
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 2554
      MYSQL_DATABASE: blog
    networks:
      - backend-network

  # Backend
  blog:
    container_name: blog-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8091:80
    environment:
      PORT: 8091
      DB_SCHEMA: blog
      DB_USER: root
      DB_PASS: 2554
    networks:
      - backend-network
    depends_on:
      - bddBlog


  phpmyadmin:
    depends_on:
      - bddBlog
    image: phpmyadmin
    restart: always
    ports:
      - "8094:80"
    environment:
      PMA_HOST: bddBlog
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
