version: "3.7"
services:
  blog_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - ./upload-dir:/app/upload-dir

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: amila_one
      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: Amila_Rpw
    volumes :
      -  blog_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

networks:
  springapimysql-net:


volumes:
  blog_data:
  upload_dir: