version: "3"

services:
  # Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3307:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: 25542554
      MYSQL_ROOT_USER: root
      DB_SCHEMA: ${MYSQL_DATABASE}
    networks:
      - backend-network

  # Backend
  blog-service:
    container_name: blog-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  ${BLOG_PORT}:${BLOG_PORT}
    environment:
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend-network
    depends_on:
      - bdd

  phpmyadmin:
    depends_on:
      - bdd
    image: phpmyadmin
    restart: always
    ports:
      - "8094:80"
    environment:
      PMA_HOST: bdd
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge

volumes:
  db_data: